TITLE 3lab			(AddSub.asm)

INCLUDE Irvine32.inc

MONDAY		EQU	<1>
TUESDAY		EQU	<2>
WEDNESDAY	EQU	<3>
THURSDAY	EQU	<4>
FRIDAY		EQU	<5>
SATURDAY	EQU	<6>
SUNDAY		EQU	<7>

.data 
Array		BYTE MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY
.code
main PROC
	exit
main ENDP
END main
